export type { ImperativeOverlay, RenderOptions } from './transform'
export type { OverlayOptions, OverlayMeta, InjectionHolder } from './hooks'
export type { PropsWidthOverlays, MountOptions } from './types'
export { useOverlayMeta, useInjectHolder } from './hooks'
export { defineOverlay, renderOverlay } from './transform'
